


#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using Sitecore.Foundation.ORM;



namespace Sitecore.Feature.PageContent.Feature.PageContent
{


    /// <summary>
    /// I_HasPageContent Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Feature/PageContent/_HasPageContent</para>	
    /// <para>ID: af74a00b-8ca7-4c9a-a5c1-156a68590ee2</para>	
    /// </summary>
    [SitecoreType(TemplateId=I_HasPageContentConstants.TemplateIdString, Cachable=false)]
    public partial interface I_HasPageContent : IGlassBase 
    {
                                /// <summary>
                    /// The Body field.
                    /// <para></para>
                    /// <para>Field Type: Rich Text</para>		
                    /// <para>Field ID: d74f396d-5c5e-4916-bd0a-bfd58b6b1967</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(I_HasPageContentConstants.BodyFieldName)]
                    string Body  {get; set;}
            
                                /// <summary>
                    /// The Image field.
                    /// <para></para>
                    /// <para>Field Type: Image</para>		
                    /// <para>Field ID: 9492e0bb-9df9-46e7-8188-ec795c4ade44</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(I_HasPageContentConstants.ImageFieldName)]
                    Image Image  {get; set;}
            
                                /// <summary>
                    /// The Summary field.
                    /// <para></para>
                    /// <para>Field Type: Rich Text</para>		
                    /// <para>Field ID: ac3fd4db-8266-476d-9635-67814d91e901</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(I_HasPageContentConstants.SummaryFieldName)]
                    string Summary  {get; set;}
            
                                /// <summary>
                    /// The Title field.
                    /// <para></para>
                    /// <para>Field Type: Single-Line Text</para>		
                    /// <para>Field ID: c30a013f-3cc8-4961-9837-1c483277084a</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(I_HasPageContentConstants.TitleFieldName)]
                    string Title  {get; set;}
            
                }


    public static partial class I_HasPageContentConstants{

            public const string TemplateIdString = "af74a00b-8ca7-4c9a-a5c1-156a68590ee2";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "_HasPageContent";

                    
            public static readonly ID BodyFieldId = new ID("d74f396d-5c5e-4916-bd0a-bfd58b6b1967");
            public const string BodyFieldName = "Body";
            
                    
            public static readonly ID ImageFieldId = new ID("9492e0bb-9df9-46e7-8188-ec795c4ade44");
            public const string ImageFieldName = "Image";
            
                    
            public static readonly ID SummaryFieldId = new ID("ac3fd4db-8266-476d-9635-67814d91e901");
            public const string SummaryFieldName = "Summary";
            
                    
            public static readonly ID TitleFieldId = new ID("c30a013f-3cc8-4961-9837-1c483277084a");
            public const string TitleFieldName = "Title";
            
        	

    }

	
    /// <summary>
    /// _HasPageContent
    /// <para></para>
    /// <para>Path: /sitecore/templates/Feature/PageContent/_HasPageContent</para>	
    /// <para>ID: af74a00b-8ca7-4c9a-a5c1-156a68590ee2</para>	
    /// </summary>
    [SitecoreType(TemplateId=I_HasPageContentConstants.TemplateIdString, Cachable=false)] 
    public partial class _HasPageContent  : GlassBase, I_HasPageContent 
    {
       
                        /// <summary>
                /// The Body field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>		
                /// <para>Field ID: d74f396d-5c5e-4916-bd0a-bfd58b6b1967</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(I_HasPageContentConstants.BodyFieldName)]
                public virtual string Body  {get; set;}
                    
                        /// <summary>
                /// The Image field.
                /// <para></para>
                /// <para>Field Type: Image</para>		
                /// <para>Field ID: 9492e0bb-9df9-46e7-8188-ec795c4ade44</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(I_HasPageContentConstants.ImageFieldName)]
                public virtual Image Image  {get; set;}
                    
                        /// <summary>
                /// The Summary field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>		
                /// <para>Field ID: ac3fd4db-8266-476d-9635-67814d91e901</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(I_HasPageContentConstants.SummaryFieldName)]
                public virtual string Summary  {get; set;}
                    
                        /// <summary>
                /// The Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>		
                /// <para>Field ID: c30a013f-3cc8-4961-9837-1c483277084a</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(I_HasPageContentConstants.TitleFieldName)]
                public virtual string Title  {get; set;}
                    
        	
    }
}
